name: Release
on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft_release:
    permissions:
      contents: write # Allows this job to create releases

    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest] # Incluye ubuntu-latest para Linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

      - name: Determine version change
        id: version
        run: |
          set -e
          CURRENT=$(node -p "require('./package.json').version")
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            git show HEAD^:package.json > package_prev.json || echo '{}' > package_prev.json
            PREV=$(node -p "JSON.parse(require('fs').readFileSync('package_prev.json','utf8')).version || ''")
          else
            PREV=""
          fi
          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          echo "prev=$PREV" >> $GITHUB_OUTPUT
          if [ "$CURRENT" = "$PREV" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - run: pnpm install
        if: steps.version.outputs.changed == 'true'
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Build WASM (release)
        if: steps.version.outputs.changed == 'true'
        run: pnpm run wasm:build

      - name: Build
        if: steps.version.outputs.changed == 'true'
        run: pnpm run build
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: |
          Compile artifacts to mac and upload them to github release
        if: matrix.os == 'macos-latest'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          retry_wait_seconds: 15
          retry_on: error
          shell: "bash"
          command: |
            ./node_modules/.bin/electron-builder --mac --config --publish always

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token, automatically provided
        if: steps.version.outputs.changed == 'true'

      - name: |
          Compile artifacts to windows and upload them to github release
        if: matrix.os == 'windows-latest' && steps.version.outputs.changed == 'true'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          retry_wait_seconds: 15
          retry_on: error
          shell: "bash"
          command: |
            ./node_modules/.bin/electron-builder --win --config --publish always

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token, automatically provided

      - name: |
          Compile artifacts to linux and upload them to github release
        if: matrix.os == 'ubuntu-latest' && steps.version.outputs.changed == 'true'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          retry_wait_seconds: 15
          retry_on: error
          shell: "bash"
          command: |
            sudo apt install rpm && sudo snap install snapcraft --classic && ./node_modules/.bin/electron-builder --linux --config --publish always

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token, automatically provided
