name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft_release:
    permissions:
      contents: write # Allows this job to create releases

    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest] # Incluye ubuntu-latest para Linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      # Version check removed; releases are triggered by tags (v*)

      - run: pnpm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Build WASM (release)
        run: pnpm run wasm:build

      - name: Build
        run: pnpm run build
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: |
          Compile artifacts to mac and upload them to github release
        if: matrix.os == 'macos-latest'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          retry_wait_seconds: 15
          retry_on: error
          shell: "bash"
          command: |
            ./node_modules/.bin/electron-builder --mac --config --publish always

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token, automatically provided

      - name: |
          Compile artifacts to windows and upload them to github release
        if: matrix.os == 'windows-latest'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          retry_wait_seconds: 15
          retry_on: error
          shell: "bash"
          command: |
            ./node_modules/.bin/electron-builder --win --config --publish always

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token, automatically provided

      - name: |
          Compile artifacts to linux and upload them to github release
        if: matrix.os == 'ubuntu-latest'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          retry_wait_seconds: 15
          retry_on: error
          shell: "bash"
          command: |
            sudo apt install rpm && sudo snap install snapcraft --classic && ./node_modules/.bin/electron-builder --linux --config --publish always

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token, automatically provided
